services:
  - type: web
    name: roomscore
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: MONGO_URI
        value: mongodb+srv://Vishal:vishalVK47@cluster0.55wth1q.mongodb.net/roomscore
